INSERT INTO stock (productID, size, stock) values (26, 8, 3 );
INSERT INTO stock (productID, size, stock) values (26, 8.5, 30 );
INSERT INTO stock (productID, size, stock) values (26, 9, 14 );
INSERT INTO stock (productID, size, stock) values (26, 9.5, 44 );
INSERT INTO stock (productID, size, stock) values (26, 10, 55 );
INSERT INTO stock (productID, size, stock) values (26, 10.5, 2 );
INSERT INTO stock (productID, size, stock) values (26, 11, 24 );
INSERT INTO stock (productID, size, stock) values (26, 11.5, 10 );
INSERT INTO stock (productID, size, stock) values (26, 12, 30 );