INSERT INTO stock (productID, size, stock) values (26, 8, 0 );
INSERT INTO stock (productID, size, stock) values (26, 8.5, 0 );
INSERT INTO stock (productID, size, stock) values (26, 9, 0 );
INSERT INTO stock (productID, size, stock) values (26, 9.5, 0 );
INSERT INTO stock (productID, size, stock) values (26, 10, 0 );
INSERT INTO stock (productID, size, stock) values (26, 10.5, 0 );
INSERT INTO stock (productID, size, stock) values (26, 11, 0 );
INSERT INTO stock (productID, size, stock) values (26, 11.5, 0 );
INSERT INTO stock (productID, size, stock) values (26, 12, 0 );